export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const FETCH_INGREDIENTS_FAIL = 'FETCH_INGREDIENTS_FAIL';

export const PURCHACE_BURGER_SUCCESS = 'PURCHACE_BURGER_SUCCESS';
export const PURCHACE_BURGER_FAIL = 'PURCHASE_BURGER_FAIL';
